import pygame

damageAlterAbilities = {
	"Dry Skin": {
		"effect": {
			"absorb": 0.25,
			"immune": True,
		},
		"type": ["Water"],
	},
	"Flash Fire": {
		"effect": {
			"boost": "Fire",
			"immune": True,
		},
		"type": ["Fire"],
	},
	"Levitate": {
		"effect": {
			"immune": True,
		},
		"type": ["Ground"],
	},
	"Lightning Rod": {
		"effect": {
			"boost": "spa",
			"immune": True,
		},
		"type": ["Electric"],
	},
	"Motor Drive": {
		"effect": {
			"boost": "spe",
			"immune": True,
		},
		"type": ["Electric"],
	},
	"Thick Fat": {
		"effect": {
			"resist": True,
			"immune": False,
		},
		"type": ["Fire", "Ice"],
	},
	"Volt Absorb": {
		"effect": {
			"absorb": 0.25,
			"immune": True,
		},
		"type": ["Electric"],
	},
	"Water Absorb": {
		"effect": {
			"absorb": 0.25,
			"immune": True,
		},
		"type": ["Water"],
	},
}

statusProtectedAbilities = {
	"Immunity": "Poison",
	"Inner Focus": "Flinch",
	"Insomnia": "slp",
	"Limber": "par",
	"Oblivious": "Taunt",
	"Vital Spirit": "slp",
}

statusBoostAbilities = {
	"Guts": "atk",
	"Marvel Scale": "def",
}

hitByContactAbilities = {
	"Flame Body": {"status": "brn", "type": "Fire"},
	"Poison Point": {"status": "psn", "type": "Poison"},
	"Static": {"status": "par", "type": "Electric"},
}

BattleAbilities = {
	"adaptability": {
		"desc": "This Pokemon's moves that match one of its types have a same-type attack bonus (STAB) of 2 instead of 1.5.",
		"shortDesc": "This Pokemon's same-type attack bonus (STAB) is 2 instead of 1.5.",
		"name": "Adaptability",
		"rating": 3.5,
	},
	"aftermath": {
		"desc": "If this Pokemon is knocked out with a contact move, that move's user loses 1/4 of its maximum HP, rounded down. If any active Pokemon has the Ability Damp, this effect is prevented.",
		"shortDesc": "If this Pokemon is KOed with a contact move, that move's user loses 1/4 its max HP.",
		"name": "Aftermath",
		"onAfterDamageOrder": 1,
		"rating": 2.5,
	},
	"analytic": {
		"desc": "The power of this Pokemon's move is multiplied by 1.3 if it is the last to move in a turn. Does not affect Doom Desire and Future Sight.",
		"shortDesc": "This Pokemon's attacks have 1.3x power if it is the last to move in a turn.",
		"onBasePowerPriority": 8,
		"name": "Analytic",
		"rating": 2,
	},
	"arena trap": {
		"desc": "Prevents adjacent opposing Pokemon from choosing to switch out unless they are immune to trapping or are airborne.",
		"shortDesc": "Prevents adjacent foes from choosing to switch unless they are airborne.",
		"name": "Arena Trap",
		"rating": 4.5,
	},
	"big pecks": {
		"desc": "Prevents other Pokemon from lowering this Pokemon's Defense stat stage.",
		"shortDesc": "Prevents other Pokemon from lowering this Pokemon's Defense stat stage.",
		"name": "Big Pecks",
		"rating": 0.5,
	},
	"blaze": {
		"desc": "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its attacking stat is multiplied by 1.5 while using a Fire-type attack.",
		"shortDesc": "When this Pokemon has 1/3 or less of its max HP, its Fire attacks do 1.5x damage.",
		"onModifyAtkPriority": 5,
		"onModifySpAPriority": 5,
		"name": "Blaze",
		"rating": 2,
	},
	"bulletproof": {
		"desc": "This Pokemon is immune to ballistic moves. Ballistic moves include Bullet Seed, Octazooka, Barrage, Rock Wrecker, Zap Cannon, Acid Spray, Aura Sphere, Focus Blast, and all moves with Ball or Bomb in their name.",
		"shortDesc": "Makes user immune to ballistic moves (Shadow Ball, Sludge Bomb, Focus Blast, etc).",
		"name": "Bulletproof",
		"rating": 3,
	},
	"chlorophyll": {
		"desc": "If Sunny Day is active, this Pokemon's Speed is doubled.",	
		"shortDesc": "If Sunny Day is active, this Pokemon's Speed is doubled.",	
		"name": "Chlorophyll",
		"rating": 2.5,
	},
	"clear body": {
		"desc": "Prevents other Pokemon from lowering this Pokemon's stat stages.",
		"shortDesc": "Prevents other Pokemon from lowering this Pokemon's stat stages.",
		"name": "Clear Body",
		"rating": 2,
	},
	"cloud nine": {
		"desc": "While this Pokemon is active, the effects of weather conditions are disabled.",
		"shortDesc": "While this Pokemon is active, the effects of weather conditions are disabled.",
		"suppressWeather": True,
		"name": "Cloud Nine",
		"rating": 3,
	},
	"competitive": {
		"desc": "This Pokemon's Special Attack is raised by 2 stages for each of its stat stages that is lowered by an opposing Pokemon.",
		"shortDesc": "This Pokemon's Sp. Atk is raised by 2 for each of its stats that is lowered by a foe.",
		"name": "Competitive",
		"rating": 2.5,
	},
	"defiant": {
		"desc": "This Pokemon's Attack is raised by 2 stages for each of its stat stages that is lowered by an opposing Pokemon.",
		"shortDesc": "This Pokemon's Attack is raised by 2 for each of its stats that is lowered by a foe.",
		"name": "Defiant",
		"rating": 2.5,
	},
	"drought": {
		"desc": "On switch-in, this Pokemon summons Sunny Day.",
		"shortDesc": "On switch-in, this Pokemon summons Sunny Day.",
		"name": "Drought",
		"rating": 4.5,
	},
	"dry skin": {
		"desc": "This Pokemon is immune to Water-type moves and restores 1/4 of its maximum HP, rounded down, when hit by a Water-type move. The power of Fire-type moves is multiplied by 1.25 when used on this Pokemon. At the end of each turn, this Pokemon restores 1/8 of its maximum HP, rounded down, if the weather is Rain Dance, and loses 1/8 of its maximum HP, rounded down, if the weather is Sunny Day.",
		"shortDesc": "This Pokemon is healed 1/4 by Water, 1/8 by Rain; is hurt 1.25x by Fire, 1/8 by Sun.",
		"onBasePowerPriority": 7,
		"name": "Dry Skin",
		"rating": 3,
	},
	"early bird": {
		"desc": "This Pokemon sleeps for 1 turn instead of 2.",
		"shortDesc": "This Pokemon sleeps for 1 turn instead of 2.",
		"name": "Early Bird",
		"rating": 2.5,
	},
	"filter": {
		"desc": "This Pokemon receives 3/4 damage from supereffective attacks.",
		"shortDesc": "This Pokemon receives 3/4 damage from supereffective attacks.",
		"name": "Filter",
		"rating": 3,
	},
	"flame body": {
		"desc": "Pokemon making contact with this Pokemon will be burned.",
		"shortDesc": "Pokemon making contact with this Pokemon will be burned.",
		"name": "Flame Body",
		"rating": 2,
	},
	"flash fire": {
		"desc": "This Pokemon is immune to Fire-type moves. The first time it is hit by a Fire-type move, its attacking stat is multiplied by 1.5 while using a Fire-type attack as long as it remains active and has this Ability. If this Pokemon is frozen, it cannot be defrosted by Fire-type attacks.",
		"shortDesc": "This Pokemon's Fire attacks do 1.5x damage if hit by one Fire move; Fire immunity.",
		"effect": {
			"noCopy": True, # doesn't get copied by Baton Pass
			"onModifyAtkPriority": 5,
			"onModifySpAPriority": 5,
		},
		"name": "Flash Fire",
		"rating": 3,
		
	},
	"forewarn": {
		"desc": "On switch-in, this Pokemon is alerted to the move with the highest power, at random, known by an opposing Pokemon.",
		"shortDesc": "On switch-in, this Pokemon is alerted to the foes' move with the highest power.",
		"name": "Forewarn",
		"rating": 1,
	},
	"gluttony": {
		"desc": "When this Pokemon has 1/2 or less of its maximum HP, it uses certain Berries early.",
		"shortDesc": "When this Pokemon has 1/2 or less of its maximum HP, it uses certain Berries early.",
		"name": "Gluttony",
		"rating": 1,
	},
	"guts": {
		"desc": "If this Pokemon has a major status condition, its Attack is multiplied by 1.5; burn's physical damage halving is ignored.",
		"shortDesc": "If this Pokemon is statused, its Attack is 1.5x; ignores burn halving physical damage.",
		"onModifyAtkPriority": 5,
		"name": "Guts",
		"rating": 3,
	},
	"harvest": {
		"desc": "If the last item this Pokemon used is a Berry, it gets restored at the end of each turn.",
		"shortDesc": "If last item used is a Berry, it's restored at the end of the turn.",
		"name": "Harvest",
		"onResidualOrder": 26,
		"onResidualSubOrder": 1,
		"rating": 2.5,
	},
	"hydration": {
		"desc": "This Pokemon has its major status condition cured at the end of each turn if Rain Dance is active.",
		"shortDesc": "This Pokemon has its status cured at the end of each turn if Rain Dance is active.",
		"onResidualOrder": 5,
		"onResidualSubOrder": 1,
		"name": "Hydration",
		"rating": 2,
	},
	"hyper cutter": {
		"desc": "Prevents other Pokemon from lowering this Pokemon's Attack stat stage.",
		"shortDesc": "Prevents other Pokemon from lowering this Pokemon's Attack stat stage.",
		"name": "Hyper Cutter",
		"rating": 1.5,
	},
	"ice body": {
		"desc": "If Hail is active, this Pokemon restores 1/16 of its maximum HP, rounded down, at the end of each turn. This Pokemon takes no damage from Hail.",
		"shortDesc": "If Hail is active, this Pokemon heals 1/16 of its max HP each turn; immunity to Hail.",
		"name": "Ice Body",
		"rating": 1.5,
	},
	"immunity": {
		"desc": "This Pokemon cannot be poisoned. Gaining this Ability while poisoned cures it.",
		"shortDesc": "This Pokemon cannot be poisoned. Gaining this Ability while poisoned cures it.",
		"name": "Immunity",
		"rating": 2,
	},
	"infiltrator": {
		"desc": "This Pokemon's moves ignore substitutes and the opposing side's Reflect, Light Screen, Safeguard, and Mist.",
		"shortDesc": "Moves ignore substitutes and opposing Reflect, Light Screen, Safeguard, and Mist.",
		"name": "Infiltrator",
		"rating": 3,
	},
	"inner focus": {
		"desc": "This Pokemon cannot be made to flinch.",
		"shortDesc": "This Pokemon cannot be made to flinch.",
		"onFlinch": False,
		"name": "Inner Focus",
		"rating": 1.5,
	},
	"insomnia": {
		"desc": "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.",
		"shortDesc": "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.",
		"name": "Insomnia",
		"rating": 2,
	},
	"intimidate": {
		"desc": "On switch-in, this Pokemon lowers the Attack of adjacent opposing Pokemon by 1 stage. Pokemon behind a substitute are immune.",
		"shortDesc": "On switch-in, this Pokemon lowers the Attack of adjacent opponents by 1 stage.",
		"name": "Intimidate",
		"rating": 3.5,
	},
	"iron barbs": {
		"desc": "Pokemon making contact with this Pokemon lose 1/8 of their maximum HP, rounded down.",
		"shortDesc": "Pokemon making contact with this Pokemon lose 1/8 of their max HP.",
		"onAfterDamageOrder": 1,
		"name": "Iron Barbs",
		"rating": 3,
	},
	"iron fist": {
		"desc": "This Pokemon's punch-based attacks have their power multiplied by 1.2.",
		"shortDesc": "This Pokemon's punch-based attacks have 1.2x power. Sucker Punch is not boosted.",
		"onBasePowerPriority": 8,
		"name": "Iron Fist",
		"rating": 3,
	},
	"justified": {
		"desc": "This Pokemon's Attack is raised by 1 stage after it is damaged by a Dark-type move.",
		"shortDesc": "This Pokemon's Attack is raised by 1 stage after it is damaged by a Dark-type move.",
		"name": "Justified",
		"rating": 2,
	},
	"levitate": {
		"desc": "This Pokemon is immune to Ground. Gravity, Ingrain, Smack Down, Thousand Arrows, and Iron Ball nullify the immunity.",
		"shortDesc": "This Pokemon is immune to Ground; Gravity/Ingrain/Smack Down/Iron Ball nullify it.",
		"name": "Levitate",
		"rating": 3.5,
	},
	"lightning rod": {
		"desc": "This Pokemon is immune to Electric-type moves and raises its Special Attack by 1 stage when hit by an Electric-type move. If this Pokemon is not the target of a single-target Electric-type move used by another Pokemon, this Pokemon redirects that move to itself if it is within the range of that move.",
		"shortDesc": "This Pokemon draws Electric moves to itself to raise Sp. Atk by 1; Electric immunity.",
		"name": "Lightning Rod",
		"rating": 3.5,
	},
	"limber": {
		"desc": "This Pokemon cannot be paralyzed. Gaining this Ability while paralyzed cures it.",
		"shortDesc": "This Pokemon cannot be paralyzed. Gaining this Ability while paralyzed cures it.",
		"name": "Limber",
		"rating": 1.5,
	},
	"liquid ooze": {
		"desc": "This Pokemon damages those draining HP from it for as much as they would heal.",
		"shortDesc": "This Pokemon damages those draining HP from it for as much as they would heal.",
		"name": "Liquid Ooze",
		"rating": 1.5,
	},
	"magic bounce": {
		"desc": "This Pokemon blocks certain status moves and instead uses the move against the original user.",
		"shortDesc": "This Pokemon blocks certain status moves and bounces them back to the user.",
		"name": "Magic Bounce",
		"onTryHitPriority": 1,
		"effect": {
			"duration": 1,
		},
		"rating": 4.5,
	},
	"magic guard": {
		"desc": "This Pokemon can only be damaged by direct attacks. Curse and Substitute on use, Belly Drum, Pain Split, Struggle recoil, and confusion damage are considered direct damage.",
		"shortDesc": "This Pokemon can only be damaged by direct attacks.",
		"name": "Magic Guard",
		"rating": 4.5,
	},
	"magnet pull": {
		"desc": "Prevents adjacent opposing Steel-type Pokemon from choosing to switch out unless they are immune to trapping.",
		"shortDesc": "Prevents adjacent Steel-type foes from choosing to switch.",
		"name": "Magnet Pull",
		"rating": 4.5,
	},
	"marvel scale": {
		"desc": "If this Pokemon has a major status condition, its Defense is multiplied by 1.5.",
		"shortDesc": "If this Pokemon is statused, its Defense is 1.5x.",
		"onModifyDefPriority": 6,
		"name": "Marvel Scale",
		"rating": 2.5,
	},
	"mold breaker": {
		"desc": "This Pokemon's moves and their effects ignore the Abilities of other Pokemon.",
		"shortDesc": "This Pokemon's moves and their effects ignore the Abilities of other Pokemon.",
		"name": "Mold Breaker",
		"rating": 3.5,
	},
	"motor drive": {
		"desc": "This Pokemon is immune to Electric-type moves and raises its Speed by 1 stage when hit by an Electric-type move.",
		"shortDesc": "This Pokemon's Speed is raised 1 stage if hit by an Electric move; Electric immunity.",
		"name": "Motor Drive",
		"rating": 3,
	},
	"moxie": {
		"desc": "This Pokemon's Attack is raised by 1 stage if it attacks and knocks out another Pokemon.",
		"shortDesc": "This Pokemon's Attack is raised by 1 stage if it attacks and KOes another Pokemon.",
		"name": "Moxie",
		"rating": 3.5,
	},
	"multiscale": {
		"desc": "If this Pokemon is at full HP, damage taken from attacks is halved.",
		"shortDesc": "If this Pokemon is at full HP, damage taken from attacks is halved.",
		"name": "Multiscale",
		"rating": 4,
	},
	"natural cure": {
		"desc": "This Pokemon has its major status condition cured when it switches out.",
		"shortDesc": "This Pokemon has its major status condition cured when it switches out.",
		"name": "Natural Cure",
		"rating": 3.5,
	},
	"oblivious": {
		"desc": "This Pokemon cannot be taunted or encored. Gaining this Ability while affected cures it.",
		"shortDesc": "This Pokemon cannot be taunted or encored. Gaining this Ability cures it.",
		"name": "Oblivious",
		"rating": 1,
	},
	"overcoat": {
		"desc": "This Pokemon is immune to powder moves and damage from Sandstorm or Hail.",
		"shortDesc": "This Pokemon is immune to powder moves and damage from Sandstorm or Hail.",
		"onTryHitPriority": 1,
		"name": "Overcoat",
		"rating": 2.5,
	},
	"overgrow": {
		"desc": "When this Pokemon has 1/3 or less of its maximum HP, its attacking stat is multiplied by 1.5 while using a Grass-type attack.",
		"shortDesc": "When this Pokemon has 1/3 or less of its max HP, its Grass attacks do 1.5x damage.",
		"onModifyAtkPriority": 5,
		"onModifySpAPriority": 5,
		"name": "Overgrow",
		"rating": 2,
	},
	"poison point": {
		"desc": "A Pokemon making contact with this Pokemon will be poisoned.",
		"shortDesc": "A Pokemon making contact with this Pokemon will be poisoned.",
		"name": "Poison Point",
		"rating": 2,
	},
	"poison touch": {
		"desc": "This Pokemon's contact moves poison the target.",
		"shortDesc": "This Pokemon's contact moves poison the target.",
		"name": "Poison Touch",
		"rating": 2,
	},
	"prankster": {
		"desc": "This Pokemon's Status moves have priority raised by 1, but Dark types are immune.",
		"shortDesc": "This Pokemon's Status moves have priority raised by 1, but Dark types are immune.",
		"name": "Prankster",
		"rating": 4,
	},
	"reckless": {
		"desc": "This Pokemon's attacks with recoil or crash damage have their power multiplied by 1.2. Does not affect Struggle.",
		"shortDesc": "This Pokemon's attacks with recoil or crash damage have 1.2x power; not Struggle.",
		"onBasePowerPriority": 8,
		"name": "Reckless",
		"rating": 3,
	},
	"regenerator": {
		"desc": "This Pokemon restores 1/3 of its maximum HP, rounded down, when it switches out.",
		"shortDesc": "This Pokemon restores 1/3 of its maximum HP, rounded down, when it switches out.",
		"name": "Regenerator",
		"rating": 4,
	},
	"rock head": {
		"desc": "This Pokemon does not take recoil damage besides Struggle, Life Orb, and crash damage.",
		"shortDesc": "This Pokemon does not take recoil damage besides Struggle/Life Orb/crash damage.",
		"name": "Rock Head",
		"rating": 3,
	},
	"rough skin": {
		"desc": "Pokemon making contact with this Pokemon lose 1/8 of their maximum HP, rounded down.",
		"shortDesc": "Pokemon making contact with this Pokemon lose 1/8 of their max HP.",
		"onAfterDamageOrder": 1,
		"name": "Rough Skin",
		"rating": 3,
	},
	"sand rush": {
		"desc": "If Sandstorm is active, this Pokemon's Speed is doubled. This Pokemon takes no damage from Sandstorm.",
		"shortDesc": "If Sandstorm is active, this Pokemon's Speed is doubled; immunity to Sandstorm.",
		"name": "Sand Rush",
		"rating": 2.5,
	},
	"scrappy": {
		"desc": "This Pokemon can hit Ghost types with Normal- and Fighting-type moves.",
		"shortDesc": "This Pokemon can hit Ghost types with Normal- and Fighting-type moves.",
		"onModifyMovePriority": -5,
		"name": "Scrappy",
		"rating": 3,
	},
	"sheer force": {
		"desc": "This Pokemon's attacks have their power multiplied by 1.15, but the secondary effects are removed.",
		"shortDesc": "This Pokemon's attacks have 1.15x power; nullifies the effects.",
		"effect": {
			"duration": 1,
			"onBasePowerPriority": 8,
		},
		"name": "Sheer Force",
		"rating": 4,
	},
	"sniper": {
		"desc": "This pokemon's damage is multiplied by 1.5 on targets that switch in.",
		"shortDesc": "This pokemon's damage is multiplied by 1.5 on targets that switch in.",
		"name": "Sniper",
		"rating": 1,
	},
	"solar power": {
		"desc": "If Sunny Day is active, this Pokemon's Special Attack is multiplied by 1.5 and it loses 1/8 of its maximum HP, rounded down, at the end of each turn.",
		"shortDesc": "If Sunny Day is active, this Pokemon's Sp. Atk is 1.5x; loses 1/8 max HP per turn.",
		"onModifySpAPriority": 5,
		"name": "Solar Power",
		"rating": 1.5,
	},
	"solid rock": {
		"desc": "This Pokemon receives 3/4 damage from supereffective attacks.",
		"shortDesc": "This Pokemon receives 3/4 damage from supereffective attacks.",
		"name": "Solid Rock",
		"rating": 3,
	},
	"soundproof": {
		"desc": "This Pokemon is immune to sound-based moves, including Heal Bell.",
		"shortDesc": "This Pokemon is immune to sound-based moves, including Heal Bell.",
		"name": "Soundproof",
		"rating": 2,
	},
	"static": {
		"desc": "A Pokemon making contact with this Pokemon will be paralyzed.",
		"shortDesc": "Pokemon making contact with this Pokemon will be paralyzed.",
		"name": "Static",
		"rating": 2,
	},
	"sturdy": {
		"desc": "If this Pokemon is at full HP, it survives one hit with at least 1 HP. OHKO moves fail when used against this Pokemon.",
		"shortDesc": "If this Pokemon is at full HP, it survives one hit with at least 1 HP. Immune to OHKO.",
		"onDamagePriority": -100,
		"name": "Sturdy",
		"rating": 3,
	},
	"swarm": {
		"desc": "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its attacking stat is multiplied by 1.5 while using a STAB attack.",
		"shortDesc": "When this Pokemon has 1/3 or less of its max HP, its STAB attacks do 1.5x damage.",
		"onModifyAtkPriority": 5,
		"onModifySpAPriority": 5,
		"name": "Swarm",
		"rating": 2,
	},
	"swift swim": {
		"desc": "If Rain Dance is active, this Pokemon's Speed is doubled.",
		"shortDesc": "If Rain Dance is active, this Pokemon's Speed is doubled.",
		"name": "Swift Swim",
		"rating": 2.5,
	},
	"synchronize": {
		"desc": "If another Pokemon burns, paralyzes, poisons, or badly poisons this Pokemon, that Pokemon receives the same major status condition.",
		"shortDesc": "If another Pokemon burns/poisons/paralyzes this Pokemon, it also gets that status.",
		"name": "Synchronize",
		"rating": 2.5,
	},
	"technician": {
		"desc": "This Pokemon's moves of 60 power or less have their power multiplied by 1.5. Does affect Struggle.",
		"shortDesc": "This Pokemon's moves of 60 power or less have 1.5x power. Includes Struggle.",
		"onBasePowerPriority": 8,
		"name": "Technician",
		"rating": 4,
	},
	"thick fat": {
		"desc": "If a Pokemon uses a Fire- or Ice-type attack against this Pokemon, that Pokemon's attacking stat is halved when calculating the damage to this Pokemon.",
		"shortDesc": "Fire/Ice-type moves against this Pokemon deal damage with a halved attacking stat.",
		"onModifyAtkPriority": 6,
		"onModifySpAPriority": 5,
		"name": "Thick Fat",
		"rating": 3.5,
	},
	"tinted lens": {
		"desc": "This Pokemon's attacks that are not very effective on a target deal double damage.",
		"shortDesc": "This Pokemon's attacks that are not very effective on a target deal double damage.",
		"name": "Tinted Lens",
		"rating": 3.5,
	},
	"torrent": {
		"desc": "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its attacking stat is multiplied by 1.5 while using a STAB attack.",
		"shortDesc": "When this Pokemon has 1/3 or less of its max HP, its STAB attacks do 1.5x damage.",
		"onModifyAtkPriority": 5,
		"onModifySpAPriority": 5,
		"name": "Torrent",
		"rating": 2,
	},
	"trace": {
		"desc": "On switch-in, this Pokemon copies a random adjacent opposing Pokemon's Ability. If there is no Ability that can be copied at that time, this Ability will activate as soon as an Ability can be copied. Abilities that cannot be copied are Comatose, Disguise, Flower Gift, Forecast, Illusion, Imposter, Multitype, Schooling, Stance Change, Trace, and Zen Mode.",
		"shortDesc": "On switch-in, or when it can, this Pokemon copies a random adjacent foe's Ability.",
		"name": "Trace",
		"rating": 3,
	},
	"unaware": {
		"desc": "This Pokemon ignores other Pokemon's Attack, Special Attack, and accuracy stat stages when taking damage, and ignores other Pokemon's Defense, Special Defense, and evasiveness stat stages when dealing damage.",
		"shortDesc": "This Pokemon ignores other Pokemon's stat stages when taking or doing damage.",
		"name": "Unaware",
		"rating": 3,
	},
	"unburden": {
		"desc": "If this Pokemon loses its held item for any reason, its Speed is doubled. This boost is lost if it switches out or gains a new item or Ability.",
		"shortDesc": "Speed is doubled on held item loss; boost is lost if it switches, gets new item/Ability.",
		"name": "Unburden",
		"rating": 3.5,
	},
	"unnerve": {
		"desc": "While this Pokemon is active, it prevents opposing Pokemon from using their Berries.",
		"shortDesc": "While this Pokemon is active, it prevents opposing Pokemon from using their Berries.",
		"onFoeTryEatItem": False,
		"name": "Unnerve",
		"rating": 1.5,
	},
	"vital spirit": {
		"desc": "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.",
		"shortDesc": "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.",
		"name": "Vital Spirit",
		"rating": 2,
	},
	"volt absorb": {
		"desc": "This Pokemon is immune to Electric-type moves and restores 1/4 of its maximum HP, rounded down, when hit by an Electric-type move.",
		"shortDesc": "This Pokemon heals 1/4 of its max HP when hit by Electric moves; Electric immunity.",
		"name": "Volt Absorb",
		"rating": 3.5,
	},
	"water absorb": {
		"desc": "This Pokemon is immune to Water-type moves and restores 1/4 of its maximum HP, rounded down, when hit by a Water-type move.",
		"shortDesc": "This Pokemon heals 1/4 of its max HP when hit by Water moves; Water immunity.",
		"name": "Water Absorb",
		"rating": 3.5,
	},
	"weak armor": {
		"desc": "If a physical attack hits this Pokemon, its Defense is lowered by 1 stage and its Speed is raised by 2 stages.",
		"shortDesc": "If a physical attack hits this Pokemon, Defense is lowered by 1, Speed is raised by 2.",
		"name": "Weak Armor",
		"rating": 1,
	},
}