import pygame

'''

List of flags and their descriptions:

authentic: Ignores a target's substitute.
bite: Power is multiplied by 1.5 when used by a Pokemon with the Ability Strong Jaw.
bullet: Has no effect on Pokemon with the Ability Bulletproof.
charge: The user is unable to make a move between turns.
contact: Makes contact.
defrost: Thaws the user if executed successfully while the user is frozen.
gravity: Prevented from being executed or selected during Gravity's effect.
heal: Prevented from being executed or selected during Heal Block's effect.
mirror: Can be copied by Mirror Move.
powder: Has no effect on Grass-type Pokemon, Pokemon with the Ability Overcoat, and Pokemon holding Safety Goggles.
protect: Blocked by Detect, Protect, Spiky Shield, and if not a Status move, King's Shield.
pulse: Power is multiplied by 1.5 when used by a Pokemon with the Ability Mega Launcher.
punch: Power is multiplied by 1.2 when used by a Pokemon with the Ability Iron Fist.
recharge: If this move is successful, the user must recharge on the following turn and cannot make a move.
reflectable: Bounced back to the original user by Magic Coat or the Ability Magic Bounce.
snatch: Can be stolen from the original user and instead used by another Pokemon using Snatch.
sound: Has no effect on Pokemon with the Ability Soundproof.

'''

contactImages = {
	
	"Physical": pygame.image.load('images/physical.png'),
       
	"Special": pygame.image.load('images/special.png'),
       
	"Status": pygame.image.load('images/other.png')
}

movedex = {
	"aerialace": {
		"basePower": 60,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Aerial Ace",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Flying",
		"zMovePower": 120,
	},
	"ancientpower": {
		"basePower": 60,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Ancient Power",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Rock",
		"zMovePower": 120,
	},
	"aquajet": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Aqua Jet",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 100,
	},
	"aquatail": {
		"basePower": 90,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Aqua Tail",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 175,
	},
	"aurasphere": {
		"basePower": 80,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Aura Sphere",
		"priority": 0,
		"flags": {"bullet": 1, "protect": 1, "pulse": 1, "mirror": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 160,
	},
	"avalanche": {
		"basePower": 60,
		"category": "Physical",
		"desc": "Power doubles if the user was hit by the target this turn.",
		"shortDesc": "Power doubles if user is damaged by the target.",
		"name": "Avalanche",
		"priority": -4,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 120,
	},
	"bite": {
		"basePower": 60,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Bite",
		"priority": 0,
		"flags": {"bite": 1, "contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Dark",
		"zMovePower": 120,
	},
	"bonemerang": {
		"basePower": 50,
		"category": "Physical",
		"desc": "Hits twice. If the first hit breaks the target's substitute, it will take damage for the second hit.",
		"shortDesc": "Hits 2 times in one turn.",
		"name": "Bonemerang",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"multihit": 2,
		"secondary": False,
		"type": "Ground",
		"zMovePower": 100,
	},
	"bravebird": {
		"basePower": 120,
		"category": "Physical",
		"desc": "If the target lost HP, the user takes recoil damage equal to 33% the HP lost by the target, rounded half up, but not less than 1 HP.",
		"shortDesc": "Has 33% recoil.",
		"name": "Brave Bird",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"recoil": [33, 100],
		"secondary": False,
		"type": "Flying",
		"zMovePower": 190,
	},
	"brickbreak": {
		"basePower": 75,
		"category": "Physical",
		"desc": "If this attack hits, the effects of Reflect, Light Screen, and Aurora Veil end for the target's side of the field before damage is calculated.",
		"shortDesc": "Destroys screens, unless the target is immune.",
		"name": "Brick Break",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 140,
	},
	"bugbuzz": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Bug Buzz",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1, "sound": 1, "authentic": 1},
		"secondary": False,
		"type": "Bug",
		"zMovePower": 175,
	},
	"bulletpunch": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Bullet Punch",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1},
		"secondary": False,
		"type": "Steel",
		"zMovePower": 100,
	},
	"closecombat": {
		"basePower": 120,
		"category": "Physical",
		"desc": "Lowers the user's Defense and Special Defense by 1 stage.",
		"shortDesc": "Lowers the user's Defense and Sp. Def by 1.",
		"name": "Close Combat",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 190,
	},
	"crabhammer": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Crabhammer",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 180,
	},
	"crosschop": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Cross Chop",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 180,
	},
	"crunch": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Crunch",
		"priority": 0,
		"flags": {"bite": 1, "contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Dark",
		"zMovePower": 160,
	},
	"dazzlinggleam": {
		"basePower": 80,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Dazzling Gleam",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fairy",
		"zMovePower": 160,
	},
	"doubleedge": {
		"basePower": 120,
		"category": "Physical",
		"desc": "If the target lost HP, the user takes recoil damage equal to 33% the HP lost by the target, rounded half up, but not less than 1 HP.",
		"shortDesc": "Has 33% recoil.",
		"name": "Double-Edge",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"recoil": [33, 100],
		"secondary": False,
		"type": "Normal",
		"zMovePower": 190,
	},
	"dragonpulse": {
		"basePower": 85,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Dragon Pulse",
		"priority": 0,
		"flags": {"protect": 1, "pulse": 1, "mirror": 1},
		"secondary": False,
		"type": "Dragon",
		"zMovePower": 160,
	},
	"dragonrush": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Dragon Rush",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Dragon",
		"zMovePower": 180,
	},
	"drainpunch": {
		"basePower": 75,
		"category": "Physical",
		"desc": "The user recovers 1/2 the HP lost by the target, rounded half up.",# If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.",
		"shortDesc": "User recovers 50% of the damage dealt.",
		"name": "Drain Punch",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1, "heal": 1},
		"drain": [1, 2],
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 140,
	},
	"drillpeck": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Drill Peck",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Flying",
		"zMovePower": 160,
	},
	"drillrun": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Drill Run",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ground",
		"zMovePower": 160,
	},
	"earthpower": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Earth Power",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ground",
		"zMovePower": 175,
	},
	"earthquake": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Earthquake",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ground",
		"zMovePower": 180,
	},
	"encore": {
		"basePower": 0,
		"category": "Status",
		"desc": "For 3 turns, the target is forced to repeat its last move used. If the affected move runs out of PP, the effect ends. Fails if the target is already under this effect, if it has not made a move, if the move has 0 PP, or if the move is Encore, Mimic, Mirror Move, Sketch, Struggle, or Transform.",
		"shortDesc": "The target repeats its last move for 3 turns.",
		"name": "Encore",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1, "authentic": 1},
		"effect": {
			"duration": 3,
			"noCopy": True, # doesn't get copied by Z-Baton Pass
			"onResidualOrder": 13,
		},
		"secondary": {"volatileStatus": 'encore',},
		"type": "Normal",
		"zMoveBoost": {"spe": 1},
	},
	"energyball": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Energy Ball",
		"priority": 0,
		"flags": {"bullet": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Grass",
		"zMovePower": 175,
	},
	"extremespeed": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Nearly always goes first.",
		"name": "Extreme Speed",
		"priority": 2,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 160,		
	},
	"fakeout": {
		"basePower": 40,
		"category": "Physical",
		"desc": "Has a 100% chance to flinch the target. Fails unless it is the user's first turn on the field.",
		"shortDesc": "Hits first. First turn out only. 100% flinch chance.",
		"name": "Fake Out",
		"priority": 3,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": {"volatileStatus": 'flinch',},
		"type": "Normal",
		"zMovePower": 100,
	},
	"firepunch": {
		"basePower": 75,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Fire Punch",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1},
		"secondary": False,
		"type": "Fire",
		"zMovePower": 140,
	},
	"flail": {
		"basePower": 100,
		"category": "Physical",
		"desc": "Deals damage to the target based on the amount of HP the user has left. X is equal to (user's current HP * 48 / user's maximum HP), rounded down; the base power of this attack is 20 if X is 33 to 48, 40 if X is 17 to 32, 80 if X is 10 to 16, 100 if X is 5 to 9, 150 if X is 2 to 4, and 200 if X is 0 or 1.",
		"shortDesc": "More power the less HP the user has left.",
		"name": "Flail",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 160,
	},
	"flamewheel": {
		"basePower": 60,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Thaws user.",
		"name": "Flame Wheel",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "defrost": 1},
		"secondary": False,
		"type": "Fire",
		"zMovePower": 120,
	},
	"flamethrower": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Flamethrower",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fire",
		"zMovePower": 175,
	},
	"flareblitz": {
		"basePower": 120,
		"category": "Physical",
		"desc": "If the target lost HP, the user takes recoil damage equal to 33% the HP lost by the target, rounded half up, but not less than 1 HP.",
		"shortDesc": "Has 33% recoil. Thaws user.",
		"name": "Flare Blitz",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "defrost": 1},
		"recoil": [33, 100],
		"secondary": False,
		"type": "Fire",
		"zMovePower": 190,
	},
	"flashcannon": {
		"basePower": 80,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Flash Cannon",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Steel",
		"zMovePower": 160,
	},
	"foulplay": {
		"basePower": 95,
		"category": "Physical",
		"desc": "Damage is calculated using the target's Attack stat, including stat stage changes. The user's Ability, item, and burn are used as normal.",
		"shortDesc": "Uses target's Attack stat in damage calculation.",
		"name": "Foul Play",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"useTargetOffensive": True,
		"secondary": False,
		"type": "Dark",
		"zMovePower": 175,
	},
	"freezedry": {
		"basePower": 70,
		"category": "Special",
		"desc": "This move's type effectiveness against Water is changed to be super effective no matter what this move's type is.",
		"shortDesc": "Super effective on Water.",
		"name": "Freeze-Dry",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 140,
	},
	"gigadrain": {
		"basePower": 75,
		"category": "Special",
		"desc": "The user recovers 1/2 the HP lost by the target, rounded half up.",# If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.",
		"shortDesc": "User recovers 50% of the damage dealt.",
		"name": "Giga Drain",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1, "heal": 1},
		"drain": [1, 2],
		"secondary": False,
		"type": "Grass",
		"zMovePower": 140,
	},
	"heatwave": {
		"basePower": 95,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Heat Wave",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fire",
		"zMovePower": 175,
	},
	"hurricane": {
		"basePower": 110,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Hurricane",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Flying",
		"zMovePower": 185,
	},
	"hydropump": {
		"basePower": 110,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Hydro Pump",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 185,
	},
	"hypervoice": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Hyper Voice",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1, "sound": 1, "authentic": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 175,
	},
	"hypnosis": {
		"basePower": 0,
		"category": "Status",
		"desc": "Causes the target to fall asleep for 2 turns.",
		"shortDesc": "Puts the target to sleep for 2 turns.",
		"name": "Hypnosis",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'slp',
		"secondary": False,
		"type": "Psychic",
		"zMoveBoost": {"spe": 1},
	},
	"icebeam": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Ice Beam",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 175,
	},
	"icefang": {
		"basePower": 65,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Ice Fang",
		"priority": 0,
		"flags": {"bite": 1, "contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 120,
	},
	"icepunch": {
		"basePower": 75,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Ice Punch",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 140,
	},
	"iceshard": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Ice Shard",
		"priority": 1,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ice",
		"zMovePower": 100,
	},
	"ironhead": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Iron Head",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Steel",
		"zMovePower": 160,
	},
	"irontail": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Iron Tail",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Steel",
		"zMovePower": 180,
	},
	"jumpkick": {
		"basePower": 100,
		"category": "Physical",
		"desc": "If this attack is not successful, the user loses half of its maximum HP, rounded down, as crash damage. Pokemon with the Ability Magic Guard are unaffected by crash damage.",
		"shortDesc": "User is hurt by 50% of its max HP if it misses.",
		"name": "Jump Kick",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "gravity": 1},
		"hasCustomRecoil": True,
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 180,
	},
	"knockoff": {
		"basePower": 65,
		"category": "Physical",
		"desc": "If the target is holding an item that can be removed from it, ignoring the Ability Sticky Hold, this move's power is multiplied by 1.5. If the user has not fainted, the target loses its held item. This move cannot remove Z-Crystals, cause Pokemon with the Ability Sticky Hold to lose their held item, cause Pokemon that can Mega Evolve to lose the Mega Stone for their species, or cause a Kyogre, a Groudon, a Giratina, an Arceus, a Genesect, or a Silvally to lose their Blue Orb, Red Orb, Griseous Orb, Plate, Drive, or Memory respectively. Items lost to this move cannot be regained with Recycle or the Ability Harvest.",
		"shortDesc": "1.5x damage if foe holds an item. Removes item.",
		"name": "Knock Off",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"onBasePowerPriority": 4,
		"secondary": False,
		"type": "Dark",
		"zMovePower": 120,
	},
	"leafblade": {
		"basePower": 90,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Leaf Blade",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Grass",
		"zMovePower": 175,
	},
	"leechlife": {
		"basePower": 80,
		"category": "Physical",
		"desc": "The user recovers 1/2 the HP lost by the target, rounded half up.",# If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.",
		"shortDesc": "User recovers 50% of the damage dealt.",
		"name": "Leech Life",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "heal": 1},
		"drain": [1, 2],
		"secondary": False,
		"type": "Bug",
		"zMovePower": 160,
	},
	"leechseed": {
		"basePower": 0,
		"category": "Status",
		"desc": "The Pokemon at the user's position steals 1/8 of the target's maximum HP, rounded down, at the end of each turn.",# If Big Root is held by the recipient, the HP recovered is 1.3x normal, rounded half down. If the target uses Baton Pass, the replacement will continue being leeched. If the target switches out or uses Rapid Spin, the effect ends. Grass-type Pokemon are immune to this move on use, but not its effect.",
		"shortDesc": "1/8 of target's HP is restored to user every turn.",
		"name": "Leech Seed",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"effect": {
			"onResidualOrder": 8,
		},
		"secondary": {"volatileStatus": 'leechseed',},
		"type": "Grass",
		"zMoveEffect": 'clearnegativeboost',
	},
	"lovelykiss": {
		"basePower": 0,
		"category": "Status",
		"desc": "Causes the target to fall asleep for 2 turns.",
		"shortDesc": "Puts the target to sleep for 2 turns.",
		"name": "Lovely Kiss",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'slp',
		"secondary": False,
		"type": "Normal",
		"zMoveBoost": {"spe": 1},
	},
	"machpunch": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Mach Punch",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 100,
	},
	"magikarpsrevenge": {
		"basePower": 120,
		"category": "Physical",
		"desc": "Has a 100% chance to lower target's Defense and Special Attack by 1 stage. The user recovers 1/2 the HP lost by the target, rounded half up. If this move is successful, the weather changes to rain unless it is already in effect, and the user gains the effects of Aqua Ring and Magic Coat.",
		"shortDesc": "Does many things turn 1. Can't move turn 2.",
		"name": "Magikarp's Revenge",
		"priority": 0,
		"flags": {"contact": 1, "recharge": 1, "protect": 1, "mirror": 1},
		"drain": [1, 2],
		"volatileStatus": 'mustrecharge',
		"secondary": {
			"boosts": {
				"def": -1,
				"spa": -1,
			},
		},
		"type": "Water",
	},
	"megahorn": {
		"basePower": 120,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Megahorn",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Bug",
		"zMovePower": 190,
	},
	"moonblast": {
		"basePower": 95,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Moonblast",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fairy",
		"zMovePower": 175,
	},
	"painsplit": {
		"basePower": 0,
		"category": "Status",
		"desc": "The user and the target's HP become the average of their current HP, rounded down, but not more than the maximum HP of either one.",
		"shortDesc": "Shares HP of user and target equally.",
		"name": "Pain Split",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1, "mystery": 1},
		"secondary": False,
		"type": "Normal",
		"zMoveBoost": {"def": 1},
	},
	"poisonjab": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Poison Jab",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Poison",
		"zMovePower": 160,
	},
	"powerwhip": {
		"basePower": 120,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Power Whip",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Grass",
		"zMovePower": 190,
	},
	"psychic": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Psychic",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Psychic",
		"zMovePower": 175,
	},
	"psyshock": {
		"basePower": 80,
		"category": "Special",
		"defensiveCategory": "Physical",
		"desc": "Deals damage to the target based on its Defense instead of Special Defense.",
		"shortDesc": "Damages target based on Defense, not Sp. Def.",
		"name": "Psyshock",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Psychic",
		"zMovePower": 160,
	},
	"psystrike": {
		"basePower": 100,
		"category": "Special",
		"defensiveCategory": "Physical",
		"desc": "Deals damage to the target based on its Defense instead of Special Defense.",
		"shortDesc": "Damages target based on Defense, not Sp. Def.",
		"name": "Psystrike",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Psychic",
		"zMovePower": 180,
	},
	"quickattack": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Quick Attack",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 100,
	},
	"raindance": {
		"basePower": 0,
		"category": "Status",
		"desc": "For 5 turns, the weather becomes Rain Dance. The damage of Water-type attacks is multiplied by 1.5 and the damage of Fire-type attacks is multiplied by 0.5 during the effect. Lasts for 8 turns if the user is holding Damp Rock. Fails if the current weather is Rain Dance.",
		"shortDesc": "For 5 turns, heavy rain powers Water moves.",
		"name": "Rain Dance",
		"priority": 0,
		"flags": {},
		"weather": 'RainDance',
		"secondary": False,
		"type": "Water",
		"zMoveBoost": {"spe": 1},
	},
	"rapidspin": {
		"basePower": 20,
		"category": "Physical",
		"desc": "If this move is successful and the user has not fainted, the effects of Leech Seed and partial-trapping moves end for the user, and all hazards are removed from the user's side of the field.",
		"shortDesc": "Frees user from hazards/ partial trap/Leech Seed.",
		"name": "Rapid Spin",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 100,
	},
	"razorshell": {
		"basePower": 75,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Razor Shell",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 140,
	},
	"return": {
		"basePower": 102,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Return",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 160,
	},
	"rockslide": {
		"basePower": 75,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Rock Slide",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Rock",
		"zMovePower": 140,
	},
	"roost": {
		"basePower": 0,
		"category": "Status",
		"desc": "The user restores 1/2 of its maximum HP, rounded half up. Until the end of the turn, Flying-type users lose their Flying type and pure Flying-type users become Normal type. Does nothing if the user's HP is full.",
		"shortDesc": "Heals 50% HP. Flying-type removed 'til turn ends.",
		"name": "Roost",
		"priority": 0,
		"flags": {"snatch": 1, "heal": 1},
		"heal": [1, 2],	
		"volatileStatus": 'roost',
		"effect": {
			"duration": 1,
			# implemented in BattlePokemon#getTypes
		},
		"secondary": False,
		"type": "Flying",
		"zMoveEffect": 'clearnegativeboost',
	},
	"seedbomb": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Seed Bomb",
		"priority": 0,
		"flags": {"bullet": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Grass",
		"zMovePower": 160,
	},
	"shadowball": {
		"basePower": 80,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Shadow Ball",
		"priority": 0,
		"flags": {"bullet": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ghost",
		"zMovePower": 160,
	},
	"shadowsneak": {
		"basePower": 40,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "Usually goes first.",
		"name": "Shadow Sneak",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Ghost",
		"zMovePower": 100,
	},
	"signalbeam": {
		"basePower": 75,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Signal Beam",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Bug",
		"zMovePower": 140,
	},
	"sleeppowder": {
		"basePower": 0,
		"category": "Status",
		"desc": "Causes the target to fall asleep for 2 turns.",
		"shortDesc": "Puts the target to sleep for 2 turns.",
		"name": "Sleep Powder",
		"priority": 0,
		"flags": {"powder": 1, "protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'slp',
		"secondary": False,
		"type": "Grass",
		"zMoveBoost": {"spe": 1},
	},
	"sludgebomb": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Sludge Bomb",
		"priority": 0,
		"flags": {"bullet": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Poison",
		"zMovePower": 175,
	},
	"sludgewave": {
		"basePower": 95,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Sludge Wave",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Poison",
		"zMovePower": 175,
	},
	"spikes": {
		"basePower": 0,
		"category": "Status",
		"desc": "Sets up a hazard on the foe's side of the field, damaging each foe that switches in, unless it is a Flying-type Pokemon or has the Ability Levitate. Can be used up to three times before failing. Foes lose 1/8 of their maximum HP with one layer, 1/6 of their maximum HP with two layers, and 1/4 of their maximum HP with three layers, all rounded down. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
		"shortDesc": "Hurts grounded foes on switch-in. Max 3 layers.",
		"name": "Spikes",
		"priority": 0,
		"flags": {"reflectable": 1},
		"sideCondition": 'spikes',
		"effect": {},
		"secondary": False,
		"type": "Ground",
		"zMoveBoost": {"def": 1},
	},
	"splash": {
		"basePower": 0,
		"category": "Status",
		"desc": "Nothing happens...",
		"shortDesc": "Does nothing (but we still love it).",
		"name": "Splash",
		"priority": 0,
		"flags": {"gravity": 1},
		"secondary": False,
		"type": "Normal",
		"zMoveBoost": {"atk": 3},
	},
	"spore": {
		"basePower": 0,
		"category": "Status",
		"desc": "Causes the target to fall asleep for 2 turns.",
		"shortDesc": "Puts the target to sleep for 2 turns.",
		"name": "Spore",
		"priority": 0,
		"flags": {"powder": 1, "protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'slp',
		"secondary": False,
		"type": "Grass",
		"zMoveEffect": 'clearnegativeboost',
	},
	"stealthrock": {
		"basePower": 0,
		"category": "Status",
		"desc": "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
		"shortDesc": "Hurts foes on switch-in. Factors Rock weakness.",
		"name": "Stealth Rock",
		"priority": 0,
		"flags": {"reflectable": 1},
		"sideCondition": 'stealthrock',
		"effect": {},
		"secondary": False,
		"type": "Rock",
		"zMoveBoost": {"def": 1},
	},
	"steelwing": {
		"basePower": 70,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Steel Wing",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Steel",
		"zMovePower": 140,
	},
	"stoneedge": {
		"basePower": 100,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Stone Edge",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Rock",
		"zMovePower": 180,
	},
	"suckerpunch": {
		"basePower": 70,
		"category": "Physical",
		"desc": "Fails if the target did not select a physical attack, special attack, or Me First for use this turn, or if the target moves before the user.",
		"shortDesc": "Usually goes first. Fails if target is not attacking.",
		"name": "Sucker Punch",
		"priority": 1,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Dark",
		"zMovePower": 140,
	},
	"superpower": {
		"basePower": 120,
		"category": "Physical",
		"desc": "Lowers the user's Attack and Defense by 1 stage.",
		"shortDesc": "Lowers the user's Attack and Defense by 1.",
		"name": "Superpower",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Fighting",
		"zMovePower": 190,
	},
	"surf": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Surf",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 175,
	},
	"taunt": {
		"basePower": 0,
		"category": "Status",
		"desc": "Prevents the target from using non-damaging moves for its next three turns. Pokemon with the Ability Oblivious or protected by the Ability Aroma Veil are immune.",
		"shortDesc": "For 3 turns, the target can't use status moves.",
		"name": "Taunt",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1, "authentic": 1},
		"volatileStatus": 'taunt',
		"effect": {
			"duration": 3,
			"onResidualOrder": 12,
		},
		"secondary": False,
		"type": "Dark",
		"zMoveBoost": {"atk": 1},
	},
	"thunderpunch": {
		"basePower": 75,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Thunder Punch",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1, "punch": 1},
		"secondary": False,
		"type": "Electric",
		"zMovePower": 140,
	},
	"thunderwave": {
		"basePower": 0,
		"category": "Status",
		"desc": "Paralyzes the target.",
		"shortDesc": "Paralyzes the target.",
		"name": "Thunder Wave",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'par',
		"ignoreImmunity": False,
		"secondary": False,
		"type": "Electric",
		"zMoveBoost": {"spd": 1},
	},
	"thunderbolt": {
		"basePower": 90,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Thunderbolt",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Electric",
		"zMovePower": 175,
	},
	"toxic": {
		"basePower": 0,
		"category": "Status",
		"desc": "Badly poisons the target. If a Poison-type Pokemon uses this move, the target cannot avoid the attack, even if the target is in the middle of a two-turn move.",
		"shortDesc": "Badly poisons the target.",
		"name": "Toxic",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		# No Guard-like effect for Poison-type users implemented in BattleScripts#tryMoveHit
		"status": 'tox',
		"secondary": False,
		"type": "Poison",
		"zMoveBoost": {"def": 1},
	},
	"toxicspikes": {
		"basePower": 0,
		"category": "Status",
		"desc": "Sets up a hazard on the foe's side of the field, poisoning each foe that switches in, unless it is a Flying-type Pokemon or has the Ability Levitate. Can be used up to two times before failing. Foes become poisoned with one layer and badly poisoned with two layers. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, is hit by Defog, or a grounded Poison-type Pokemon switches in. Safeguard prevents the foe's party from being poisoned on switch-in, but a substitute does not.",
		"shortDesc": "Poisons grounded foes on switch-in. Max 2 layers.",
		"name": "Toxic Spikes",
		"priority": 0,
		"flags": {"reflectable": 1},
		"sideCondition": 'toxicspikes',
		"effect": {},
		"secondary": False,
		"type": "Poison",
		"zMoveBoost": {"def": 1},
	},
	"triattack": {
		"basePower": 80,
		"category": "Special",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Tri Attack",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Normal",
		"zMovePower": 160,
	},
	"uturn": {
		"basePower": 70,
		"category": "Physical",
		"desc": "If this move is successful and the user has not fainted, the user switches out even if it is trapped and is replaced immediately by a selected party member. The user does not switch out if there are no unfainted party members, or if the target switched out using an Eject Button.",
		"shortDesc": "User switches out after damaging the target.",
		"name": "U-turn",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"selfSwitch": True,
		"secondary": False,
		"type": "Bug",
		"zMovePower": 140,
	},
	"voltswitch": {
		"basePower": 70,
		"category": "Special",
		"desc": "If this move is successful and the user has not fainted, the user switches out even if it is trapped and is replaced immediately by a selected party member. The user does not switch out if there are no unfainted party members.",
		"shortDesc": "User switches out after damaging the target.",
		"name": "Volt Switch",
		"priority": 0,
		"flags": {"protect": 1, "mirror": 1},
		"selfSwitch": True,
		"secondary": False,
		"type": "Electric",
		"zMovePower": 140,
	},
	"volttackle": {
		"basePower": 120,
		"category": "Physical",
		"desc": "If the target lost HP, the user takes recoil damage equal to 33% the HP lost by the target, rounded half up, but not less than 1 HP.",
		"shortDesc": "Has 33% recoil.",
		"name": "Volt Tackle",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"recoil": [33, 100],
		"secondary": False,
		"type": "Electric",
		"zMovePower": 190,
	},
	"waterfall": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Waterfall",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Water",
		"zMovePower": 160,
	},
	"wildcharge": {
		"basePower": 90,
		"category": "Physical",
		"desc": "If the target lost HP, the user takes recoil damage equal to 1/4 the HP lost by the target, rounded half up, but not less than 1 HP.",
		"shortDesc": "Has 1/4 recoil.",
		"name": "Wild Charge",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"recoil": [1, 4],
		"secondary": False,
		"type": "Electric",
		"zMovePower": 175,
	},
	"willowisp": {
		"basePower": 0,
		"category": "Status",
		"desc": "Burns the target.",
		"shortDesc": "Burns the target.",
		"name": "Will-O-Wisp",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"status": 'brn',
		"secondary": False,
		"type": "Fire",
		"zMoveBoost": {"atk": 1},
	},
	"wish": {
		"basePower": 0,
		"category": "Status",
		"desc": "At the end of the next turn, the Pokemon at the user's position has 1/2 of the user's maximum HP restored to it, rounded half up. Fails if this move is already in effect for the user's position.",
		"shortDesc": "Next turn, 50% of the user's max HP is restored.",
		"name": "Wish",
		"priority": 0,
		"flags": {"snatch": 1, "heal": 1},
		"sideCondition": 'Wish',
		"effect": {
			"duration": 2,
			"onResidualOrder": 4,
		},
		"secondary": False,
		"type": "Normal",
		"zMoveBoost": {"spd": 1},
	},
	"xscissor": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "X-Scissor",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Bug",
		"zMovePower": 160,
	},
	"yawn": {
		"basePower": 0,
		"category": "Status",
		"desc": "Causes the target to fall asleep at the end of the next turn. Fails when used if the target cannot fall asleep or if it already has a major status condition. At the end of the next turn, if the target is still on the field, does not have a major status condition, and can fall asleep, it falls asleep for 2 turns. If the target becomes affected, this effect cannot be prevented by Safeguard or a substitute, or by falling asleep and waking up during the effect.",
		"shortDesc": "Puts the target to sleep after 1 turn.",
		"name": "Yawn",
		"priority": 0,
		"flags": {"protect": 1, "reflectable": 1, "mirror": 1},
		"volatileStatus": 'yawn',
		"effect": {
			"noCopy": True, # doesn't get copied by Baton Pass
			"duration": 2,
		},
		"secondary": False,
		"type": "Normal",
		"zMoveBoost": {"spe": 1},
	},
	"zenheadbutt": {
		"basePower": 80,
		"category": "Physical",
		"desc": "No additional effect.",
		"shortDesc": "No additional effect.",
		"name": "Zen Headbutt",
		"priority": 0,
		"flags": {"contact": 1, "protect": 1, "mirror": 1},
		"secondary": False,
		"type": "Psychic",
		"zMovePower": 160,
	},
}

